# Generated by Django 4.2.2 on 2023-06-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField(choices=[(1, 'Ресторан'), (2, 'Кафе'), (3, 'Бар')], default=1)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo')),
                ('description', models.TextField(blank=True, null=True)),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='places', to='geo.street')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
